test

diff --git a/.github/workflows/hexlet-check.yml b/.github/workflows/hexlet-check.yml
--- a/.github/workflows/hexlet-check.yml
+++ b/.github/workflows/hexlet-check.yml
@@ -2,25 +2,37 @@
 #                    DO NOT DELETE OR EDIT THIS FILE                     #
 #     This file is automatically generated and used to run tests         #
 ##########################################################################
-
 name: hexlet-check
-
 on:
   push:
     branches:
       - '**'
     tags:
       - '**'
-
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+
       - name: Set up Vault password
         run: echo "$ANSIBLE_VAULT_PASSWORD" > vault-pass.txt
         env:
           ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
+
+      - name: Validate vault-pass.txt exists and is not empty
+        run: |
+          if [ ! -f vault-pass.txt ]; then
+            echo "❌ Error: File 'vault-pass.txt' does NOT exist!"
+            exit 1
+          elif [ ! -s vault-pass.txt ]; then
+            echo "❌ Error: File 'vault-pass.txt' is empty!"
+            exit 1
+          else
+            echo "✅ File 'vault-pass.txt' exists and is not empty."
+            echo "📄 Contents of vault-pass.txt:"
+            cat vault-pass.txt
+          fi
 
       - name: Hexlet project check
         uses: hexlet/project-action@release
